FROM dokken/centos-stream-9
RUN yum install -y java-17-openjdk-headless && yum clean all
WORKDIR /app
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-17.0.6.0.10-3.el9.x86_64/
RUN wget https://dlcdn.apache.org/maven/maven-3/3.9.5/binaries/apache-maven-3.9.5-bin.tar.gz -P /tmp
RUN tar xf /tmp/apache-maven-3.9.5-bin.tar.gz -C /opt
RUN ln -s /opt/apache-maven-3.9.5 /opt/maven
ENV M2_HOME=/opt/maven
ENV MAVEN_HOME=/opt/maven
ENV PATH=${M2_HOME}/bin:${PATH}
COPY . .
RUN mvn clean compile
